name: Deploy Manual

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Mensagem do deploy'
        required: false
        default: 'Atualização do site'
        type: string

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
